### ISSUE TITLE
Precedence ID

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#162]
Profile, other info tab: order of precedence ID: creates the order of precedence link, but any number can be entered. The ID from the OP called ranking is easily obtainable, but is not the correct ID to get to that page of the OP. OP needs the actual op ID added visibly or the field in AMP needs a description on finding the ID. If this is being automatically pulled from the OP, then it shouldn&#039;t be editable in AMP profile.

**Comment by sueflay** [comment]
OP ID isn't pulled automatically from the OP database.  Currently, it's up to the user to supply the number that points to their entry.

Adding the description of how to find you OP ID is a good idea tho.

**Comment by jhandel** [comment]
To follow up on this..  We did look into direct link between OP and AMP but currently they don't share a common key (names are spelled differently, membership numbers are not in the OP, etc.. ) as such it is currently up to the user to make that link because we can't make it with enough confidence to do it automatically at this time.
