### ISSUE TITLE
Award Formatting

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#189]
The formatting for awards is awful to sort through. It&#039;s difficult to read mobile and desktop devices. is there a reason to not have these as a list?

The previous iteration did not list all calendar events for the next year - this seems excessive and difficult to sort through. 

Finally, this form fails in 504 Compliance - is there a reason accessibility was not taken into consideration?

**Comment by jhandel** [comment]
we use https://developer.chrome.com/docs/lighthouse/overview/ to review and consider accessibility of the solution.. 

Of a possible score of 100 the recommendations page currently scores 94 with one issue regarding the use of the role attribute without an aria-role attribute too on some tags.

We take accessibility seriously and work to improve it.. Please share your specific accessibility concerns so that we can take them under consideration.
