### ISSUE TITLE
In admin, deleting membership number prevents adding it back

### ISSUE THREAD

**Issue by BillPerkinsSca** [Ansteorra/KMP#48]
Removed my membership number, but could not zero out the date.  Now, admin and user pages show that "Membership: Information not Available"

**Comment by jhandel** [comment]
The Membership number is always editable from the edit popup. 

However the logic is updated so that when saving a member if the Membership number is empty then the following happens
1) the exp date is deleted
2) the member statis is reverted to the appropriate "unverified" state based on the members current state.
